// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="softmax_softmax,hls_ip_2021_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.984000,HLS_SYN_LAT=39,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=770,HLS_SYN_LUT=2001,HLS_VERSION=2021_1}" *)

module softmax (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Z_address0,
        Z_ce0,
        Z_q0,
        Z_address1,
        Z_ce1,
        Z_q1,
        F_address0,
        F_ce0,
        F_we0,
        F_d0,
        F_q0,
        F_address1,
        F_ce1,
        F_we1,
        F_d1,
        F_q1
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] Z_address0;
output   Z_ce0;
input  [31:0] Z_q0;
output  [3:0] Z_address1;
output   Z_ce1;
input  [31:0] Z_q1;
output  [3:0] F_address0;
output   F_ce0;
output   F_we0;
output  [31:0] F_d0;
input  [31:0] F_q0;
output  [3:0] F_address1;
output   F_ce1;
output   F_we1;
output  [31:0] F_d1;
input  [31:0] F_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] Z_address0;
reg Z_ce0;
reg Z_ce1;
reg[3:0] F_address0;
reg F_ce0;
reg F_we0;
reg[31:0] F_d0;
reg[3:0] F_address1;
reg F_ce1;
reg F_we1;
reg[31:0] F_d1;

(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] zmax_reg_294;
wire    ap_CS_fsm_state2;
wire   [5:0] grp_LOD_fu_181_ap_return;
reg   [5:0] powzmax_reg_302;
wire    ap_CS_fsm_state6;
wire   [3:0] F_addr_reg_307;
wire    ap_CS_fsm_state8;
wire   [3:0] F_addr_1_reg_312;
reg   [31:0] F_load_reg_317;
wire    ap_CS_fsm_state9;
reg   [31:0] F_load_1_reg_322;
wire   [3:0] F_addr_2_reg_327;
wire   [3:0] F_addr_3_reg_332;
reg   [31:0] F_load_2_reg_337;
wire    ap_CS_fsm_state10;
reg   [31:0] F_load_3_reg_342;
wire   [3:0] F_addr_4_reg_347;
wire   [3:0] F_addr_5_reg_352;
reg   [31:0] F_load_4_reg_357;
wire    ap_CS_fsm_state11;
reg   [31:0] F_load_5_reg_362;
wire   [3:0] F_addr_6_reg_367;
wire   [3:0] F_addr_7_reg_372;
wire  signed [31:0] sext_ln20_fu_214_p1;
reg  signed [31:0] sext_ln20_reg_377;
wire    ap_CS_fsm_state12;
reg   [31:0] F_load_6_reg_382;
reg   [31:0] F_load_7_reg_387;
wire   [3:0] F_addr_8_reg_392;
wire   [3:0] F_addr_9_reg_397;
wire   [31:0] ashr_ln23_2_fu_235_p2;
reg   [31:0] ashr_ln23_2_reg_402;
wire    ap_CS_fsm_state13;
wire   [31:0] ashr_ln23_3_fu_240_p2;
reg   [31:0] ashr_ln23_3_reg_407;
wire   [31:0] ashr_ln23_4_fu_245_p2;
reg   [31:0] ashr_ln23_4_reg_412;
wire   [31:0] ashr_ln23_5_fu_250_p2;
reg   [31:0] ashr_ln23_5_reg_417;
wire   [31:0] ashr_ln23_6_fu_255_p2;
reg   [31:0] ashr_ln23_6_reg_422;
wire   [31:0] ashr_ln23_7_fu_260_p2;
reg   [31:0] ashr_ln23_7_reg_427;
wire   [31:0] ashr_ln23_8_fu_265_p2;
reg   [31:0] ashr_ln23_8_reg_432;
wire   [31:0] ashr_ln23_9_fu_271_p2;
reg   [31:0] ashr_ln23_9_reg_437;
wire    grp_softmax_Pipeline_maxloop_fu_173_ap_start;
wire    grp_softmax_Pipeline_maxloop_fu_173_ap_done;
wire    grp_softmax_Pipeline_maxloop_fu_173_ap_idle;
wire    grp_softmax_Pipeline_maxloop_fu_173_ap_ready;
wire   [3:0] grp_softmax_Pipeline_maxloop_fu_173_Z_address0;
wire    grp_softmax_Pipeline_maxloop_fu_173_Z_ce0;
wire   [3:0] grp_softmax_Pipeline_maxloop_fu_173_Z_address1;
wire    grp_softmax_Pipeline_maxloop_fu_173_Z_ce1;
wire   [31:0] grp_softmax_Pipeline_maxloop_fu_173_select_ln10_out;
wire    grp_softmax_Pipeline_maxloop_fu_173_select_ln10_out_ap_vld;
wire    grp_LOD_fu_181_ap_start;
wire    grp_LOD_fu_181_ap_done;
wire    grp_LOD_fu_181_ap_idle;
wire    grp_LOD_fu_181_ap_ready;
reg   [31:0] grp_LOD_fu_181_num;
wire    grp_softmax_Pipeline_denloop_fu_186_ap_start;
wire    grp_softmax_Pipeline_denloop_fu_186_ap_done;
wire    grp_softmax_Pipeline_denloop_fu_186_ap_idle;
wire    grp_softmax_Pipeline_denloop_fu_186_ap_ready;
wire   [3:0] grp_softmax_Pipeline_denloop_fu_186_Z_address0;
wire    grp_softmax_Pipeline_denloop_fu_186_Z_ce0;
wire   [3:0] grp_softmax_Pipeline_denloop_fu_186_F_address0;
wire    grp_softmax_Pipeline_denloop_fu_186_F_ce0;
wire    grp_softmax_Pipeline_denloop_fu_186_F_we0;
wire   [31:0] grp_softmax_Pipeline_denloop_fu_186_F_d0;
wire   [31:0] grp_softmax_Pipeline_denloop_fu_186_den_out;
wire    grp_softmax_Pipeline_denloop_fu_186_den_out_ap_vld;
reg    grp_softmax_Pipeline_maxloop_fu_173_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [31:0] select_ln10_loc_fu_56;
reg    grp_LOD_fu_181_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_softmax_Pipeline_denloop_fu_186_ap_start_reg;
wire    ap_CS_fsm_state7;
wire   [31:0] ashr_ln23_fu_223_p2;
wire   [31:0] ashr_ln23_1_fu_229_p2;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire   [21:0] trunc_ln_fu_204_p4;
wire  signed [31:0] sext_ln20_1_fu_219_p1;
reg   [16:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
#0 grp_softmax_Pipeline_maxloop_fu_173_ap_start_reg = 1'b0;
#0 grp_LOD_fu_181_ap_start_reg = 1'b0;
#0 grp_softmax_Pipeline_denloop_fu_186_ap_start_reg = 1'b0;
end

softmax_softmax_Pipeline_maxloop grp_softmax_Pipeline_maxloop_fu_173(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_softmax_Pipeline_maxloop_fu_173_ap_start),
    .ap_done(grp_softmax_Pipeline_maxloop_fu_173_ap_done),
    .ap_idle(grp_softmax_Pipeline_maxloop_fu_173_ap_idle),
    .ap_ready(grp_softmax_Pipeline_maxloop_fu_173_ap_ready),
    .zmax(zmax_reg_294),
    .Z_address0(grp_softmax_Pipeline_maxloop_fu_173_Z_address0),
    .Z_ce0(grp_softmax_Pipeline_maxloop_fu_173_Z_ce0),
    .Z_q0(Z_q0),
    .Z_address1(grp_softmax_Pipeline_maxloop_fu_173_Z_address1),
    .Z_ce1(grp_softmax_Pipeline_maxloop_fu_173_Z_ce1),
    .Z_q1(Z_q1),
    .select_ln10_out(grp_softmax_Pipeline_maxloop_fu_173_select_ln10_out),
    .select_ln10_out_ap_vld(grp_softmax_Pipeline_maxloop_fu_173_select_ln10_out_ap_vld)
);

softmax_LOD grp_LOD_fu_181(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_LOD_fu_181_ap_start),
    .ap_done(grp_LOD_fu_181_ap_done),
    .ap_idle(grp_LOD_fu_181_ap_idle),
    .ap_ready(grp_LOD_fu_181_ap_ready),
    .num(grp_LOD_fu_181_num),
    .ap_return(grp_LOD_fu_181_ap_return)
);

softmax_softmax_Pipeline_denloop grp_softmax_Pipeline_denloop_fu_186(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_softmax_Pipeline_denloop_fu_186_ap_start),
    .ap_done(grp_softmax_Pipeline_denloop_fu_186_ap_done),
    .ap_idle(grp_softmax_Pipeline_denloop_fu_186_ap_idle),
    .ap_ready(grp_softmax_Pipeline_denloop_fu_186_ap_ready),
    .Z_address0(grp_softmax_Pipeline_denloop_fu_186_Z_address0),
    .Z_ce0(grp_softmax_Pipeline_denloop_fu_186_Z_ce0),
    .Z_q0(Z_q0),
    .sext_ln9(powzmax_reg_302),
    .F_address0(grp_softmax_Pipeline_denloop_fu_186_F_address0),
    .F_ce0(grp_softmax_Pipeline_denloop_fu_186_F_ce0),
    .F_we0(grp_softmax_Pipeline_denloop_fu_186_F_we0),
    .F_d0(grp_softmax_Pipeline_denloop_fu_186_F_d0),
    .den_out(grp_softmax_Pipeline_denloop_fu_186_den_out),
    .den_out_ap_vld(grp_softmax_Pipeline_denloop_fu_186_den_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_LOD_fu_181_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state12))) begin
            grp_LOD_fu_181_ap_start_reg <= 1'b1;
        end else if ((grp_LOD_fu_181_ap_ready == 1'b1)) begin
            grp_LOD_fu_181_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_softmax_Pipeline_denloop_fu_186_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state6) & (grp_LOD_fu_181_ap_done == 1'b1))) begin
            grp_softmax_Pipeline_denloop_fu_186_ap_start_reg <= 1'b1;
        end else if ((grp_softmax_Pipeline_denloop_fu_186_ap_ready == 1'b1)) begin
            grp_softmax_Pipeline_denloop_fu_186_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_softmax_Pipeline_maxloop_fu_173_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_softmax_Pipeline_maxloop_fu_173_ap_start_reg <= 1'b1;
        end else if ((grp_softmax_Pipeline_maxloop_fu_173_ap_ready == 1'b1)) begin
            grp_softmax_Pipeline_maxloop_fu_173_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        F_load_1_reg_322 <= F_q0;
        F_load_reg_317 <= F_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        F_load_2_reg_337 <= F_q1;
        F_load_3_reg_342 <= F_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        F_load_4_reg_357 <= F_q1;
        F_load_5_reg_362 <= F_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        F_load_6_reg_382 <= F_q1;
        F_load_7_reg_387 <= F_q0;
        sext_ln20_reg_377 <= sext_ln20_fu_214_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ashr_ln23_2_reg_402 <= ashr_ln23_2_fu_235_p2;
        ashr_ln23_3_reg_407 <= ashr_ln23_3_fu_240_p2;
        ashr_ln23_4_reg_412 <= ashr_ln23_4_fu_245_p2;
        ashr_ln23_5_reg_417 <= ashr_ln23_5_fu_250_p2;
        ashr_ln23_6_reg_422 <= ashr_ln23_6_fu_255_p2;
        ashr_ln23_7_reg_427 <= ashr_ln23_7_fu_260_p2;
        ashr_ln23_8_reg_432 <= ashr_ln23_8_fu_265_p2;
        ashr_ln23_9_reg_437 <= ashr_ln23_9_fu_271_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        powzmax_reg_302 <= grp_LOD_fu_181_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_softmax_Pipeline_maxloop_fu_173_select_ln10_out_ap_vld == 1'b1))) begin
        select_ln10_loc_fu_56 <= grp_softmax_Pipeline_maxloop_fu_173_select_ln10_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        zmax_reg_294 <= Z_q0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        F_address0 = F_addr_9_reg_397;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        F_address0 = F_addr_7_reg_372;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        F_address0 = F_addr_5_reg_352;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        F_address0 = F_addr_3_reg_332;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        F_address0 = F_addr_1_reg_312;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        F_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        F_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        F_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        F_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        F_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        F_address0 = grp_softmax_Pipeline_denloop_fu_186_F_address0;
    end else begin
        F_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        F_address1 = F_addr_8_reg_392;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        F_address1 = F_addr_6_reg_367;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        F_address1 = F_addr_4_reg_347;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        F_address1 = F_addr_2_reg_327;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        F_address1 = F_addr_reg_307;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        F_address1 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        F_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        F_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        F_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        F_address1 = 64'd0;
    end else begin
        F_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | ((1'b1 == ap_CS_fsm_state13) & (grp_LOD_fu_181_ap_done == 1'b1)))) begin
        F_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        F_ce0 = grp_softmax_Pipeline_denloop_fu_186_F_ce0;
    end else begin
        F_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | ((1'b1 == ap_CS_fsm_state13) & (grp_LOD_fu_181_ap_done == 1'b1)))) begin
        F_ce1 = 1'b1;
    end else begin
        F_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        F_d0 = ashr_ln23_9_reg_437;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        F_d0 = ashr_ln23_7_reg_427;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        F_d0 = ashr_ln23_5_reg_417;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        F_d0 = ashr_ln23_3_reg_407;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        F_d0 = ashr_ln23_1_fu_229_p2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        F_d0 = grp_softmax_Pipeline_denloop_fu_186_F_d0;
    end else begin
        F_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        F_d1 = ashr_ln23_8_reg_432;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        F_d1 = ashr_ln23_6_reg_422;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        F_d1 = ashr_ln23_4_reg_412;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        F_d1 = ashr_ln23_2_reg_402;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        F_d1 = ashr_ln23_fu_223_p2;
    end else begin
        F_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | ((1'b1 == ap_CS_fsm_state13) & (grp_LOD_fu_181_ap_done == 1'b1)))) begin
        F_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        F_we0 = grp_softmax_Pipeline_denloop_fu_186_F_we0;
    end else begin
        F_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | ((1'b1 == ap_CS_fsm_state13) & (grp_LOD_fu_181_ap_done == 1'b1)))) begin
        F_we1 = 1'b1;
    end else begin
        F_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        Z_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        Z_address0 = grp_softmax_Pipeline_denloop_fu_186_Z_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Z_address0 = grp_softmax_Pipeline_maxloop_fu_173_Z_address0;
    end else begin
        Z_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        Z_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        Z_ce0 = grp_softmax_Pipeline_denloop_fu_186_Z_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Z_ce0 = grp_softmax_Pipeline_maxloop_fu_173_Z_ce0;
    end else begin
        Z_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        Z_ce1 = grp_softmax_Pipeline_maxloop_fu_173_Z_ce1;
    end else begin
        Z_ce1 = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_LOD_fu_181_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_softmax_Pipeline_maxloop_fu_173_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_LOD_fu_181_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_softmax_Pipeline_denloop_fu_186_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_LOD_fu_181_num = sext_ln20_reg_377;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_LOD_fu_181_num = select_ln10_loc_fu_56;
    end else begin
        grp_LOD_fu_181_num = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_softmax_Pipeline_maxloop_fu_173_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_LOD_fu_181_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_softmax_Pipeline_denloop_fu_186_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (grp_LOD_fu_181_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign F_addr_1_reg_312 = 64'd1;

assign F_addr_2_reg_327 = 64'd2;

assign F_addr_3_reg_332 = 64'd3;

assign F_addr_4_reg_347 = 64'd4;

assign F_addr_5_reg_352 = 64'd5;

assign F_addr_6_reg_367 = 64'd6;

assign F_addr_7_reg_372 = 64'd7;

assign F_addr_8_reg_392 = 64'd8;

assign F_addr_9_reg_397 = 64'd9;

assign F_addr_reg_307 = 64'd0;

assign Z_address1 = grp_softmax_Pipeline_maxloop_fu_173_Z_address1;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ashr_ln23_1_fu_229_p2 = $signed(F_load_1_reg_322) >>> sext_ln20_1_fu_219_p1;

assign ashr_ln23_2_fu_235_p2 = $signed(F_load_2_reg_337) >>> sext_ln20_1_fu_219_p1;

assign ashr_ln23_3_fu_240_p2 = $signed(F_load_3_reg_342) >>> sext_ln20_1_fu_219_p1;

assign ashr_ln23_4_fu_245_p2 = $signed(F_load_4_reg_357) >>> sext_ln20_1_fu_219_p1;

assign ashr_ln23_5_fu_250_p2 = $signed(F_load_5_reg_362) >>> sext_ln20_1_fu_219_p1;

assign ashr_ln23_6_fu_255_p2 = $signed(F_load_6_reg_382) >>> sext_ln20_1_fu_219_p1;

assign ashr_ln23_7_fu_260_p2 = $signed(F_load_7_reg_387) >>> sext_ln20_1_fu_219_p1;

assign ashr_ln23_8_fu_265_p2 = $signed(F_q1) >>> sext_ln20_1_fu_219_p1;

assign ashr_ln23_9_fu_271_p2 = $signed(F_q0) >>> sext_ln20_1_fu_219_p1;

assign ashr_ln23_fu_223_p2 = $signed(F_load_reg_317) >>> sext_ln20_1_fu_219_p1;

assign grp_LOD_fu_181_ap_start = grp_LOD_fu_181_ap_start_reg;

assign grp_softmax_Pipeline_denloop_fu_186_ap_start = grp_softmax_Pipeline_denloop_fu_186_ap_start_reg;

assign grp_softmax_Pipeline_maxloop_fu_173_ap_start = grp_softmax_Pipeline_maxloop_fu_173_ap_start_reg;

assign sext_ln20_1_fu_219_p1 = $signed(grp_LOD_fu_181_ap_return);

assign sext_ln20_fu_214_p1 = $signed(trunc_ln_fu_204_p4);

assign trunc_ln_fu_204_p4 = {{grp_softmax_Pipeline_denloop_fu_186_den_out[31:10]}};

endmodule //softmax
