// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="controller_controller,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=5.790000,HLS_SYN_LAT=3789,HLS_SYN_TPT=3786,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2339,HLS_SYN_LUT=2133,HLS_VERSION=2021_1}" *)

module controller (
        ap_clk,
        ap_rst,
        A_address0,
        A_ce0,
        A_d0,
        A_q0,
        A_we0,
        A_address1,
        A_ce1,
        A_d1,
        A_q1,
        A_we1,
        B_address0,
        B_ce0,
        B_d0,
        B_q0,
        B_we0,
        B_address1,
        B_ce1,
        B_d1,
        B_q1,
        B_we1,
        C_address0,
        C_ce0,
        C_d0,
        C_q0,
        C_we0,
        C_address1,
        C_ce1,
        C_d1,
        C_q1,
        C_we1,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle
);


input   ap_clk;
input   ap_rst;
output  [5:0] A_address0;
output   A_ce0;
output  [31:0] A_d0;
input  [31:0] A_q0;
output   A_we0;
output  [5:0] A_address1;
output   A_ce1;
output  [31:0] A_d1;
input  [31:0] A_q1;
output   A_we1;
output  [5:0] B_address0;
output   B_ce0;
output  [31:0] B_d0;
input  [31:0] B_q0;
output   B_we0;
output  [5:0] B_address1;
output   B_ce1;
output  [31:0] B_d1;
input  [31:0] B_q1;
output   B_we1;
output  [5:0] C_address0;
output   C_ce0;
output  [31:0] C_d0;
input  [31:0] C_q0;
output   C_we0;
output  [5:0] C_address1;
output   C_ce1;
output  [31:0] C_d1;
input  [31:0] C_q1;
output   C_we1;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;

wire   [31:0] strm_matrix1_element_a_q0;
wire   [31:0] strm_matrix1_element_a_q1;
wire   [31:0] strm_matrix2_element_a_q0;
wire   [31:0] strm_matrix2_element_a_q1;
wire   [31:0] tmp_out_q0;
wire    Loop_VITIS_LOOP_11_1_proc4_U0_ap_start;
wire    Loop_VITIS_LOOP_11_1_proc4_U0_ap_done;
wire    Loop_VITIS_LOOP_11_1_proc4_U0_ap_continue;
wire    Loop_VITIS_LOOP_11_1_proc4_U0_ap_idle;
wire    Loop_VITIS_LOOP_11_1_proc4_U0_ap_ready;
wire   [127:0] Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix1_din;
wire    Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix1_write;
wire   [127:0] Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix2_din;
wire    Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix2_write;
wire    Loop_VITIS_LOOP_11_1_proc4_U0_start_out;
wire    Loop_VITIS_LOOP_11_1_proc4_U0_start_write;
wire   [1:0] Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix1_element_a_address0;
wire    Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix1_element_a_ce0;
wire    Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix1_element_a_we0;
wire   [31:0] Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix1_element_a_d0;
wire   [1:0] Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix1_element_a_address1;
wire    Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix1_element_a_ce1;
wire   [1:0] Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix2_element_a_address0;
wire    Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix2_element_a_ce0;
wire    Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix2_element_a_we0;
wire   [31:0] Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix2_element_a_d0;
wire   [1:0] Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix2_element_a_address1;
wire    Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix2_element_a_ce1;
wire   [5:0] Loop_VITIS_LOOP_11_1_proc4_U0_A_address0;
wire    Loop_VITIS_LOOP_11_1_proc4_U0_A_ce0;
wire   [5:0] Loop_VITIS_LOOP_11_1_proc4_U0_B_address0;
wire    Loop_VITIS_LOOP_11_1_proc4_U0_B_ce0;
wire    Loop_VITIS_LOOP_22_3_proc5_U0_ap_start;
wire    Loop_VITIS_LOOP_22_3_proc5_U0_ap_done;
wire    Loop_VITIS_LOOP_22_3_proc5_U0_ap_continue;
wire    Loop_VITIS_LOOP_22_3_proc5_U0_ap_idle;
wire    Loop_VITIS_LOOP_22_3_proc5_U0_ap_ready;
wire   [3:0] Loop_VITIS_LOOP_22_3_proc5_U0_block_out_out_address0;
wire    Loop_VITIS_LOOP_22_3_proc5_U0_block_out_out_ce0;
wire    Loop_VITIS_LOOP_22_3_proc5_U0_block_out_out_we0;
wire   [31:0] Loop_VITIS_LOOP_22_3_proc5_U0_block_out_out_d0;
wire   [3:0] Loop_VITIS_LOOP_22_3_proc5_U0_block_out_out_address1;
wire    Loop_VITIS_LOOP_22_3_proc5_U0_block_out_out_ce1;
wire    Loop_VITIS_LOOP_22_3_proc5_U0_block_out_out_we1;
wire   [31:0] Loop_VITIS_LOOP_22_3_proc5_U0_block_out_out_d1;
wire   [5:0] Loop_VITIS_LOOP_22_3_proc5_U0_C_address0;
wire    Loop_VITIS_LOOP_22_3_proc5_U0_C_ce0;
wire    Loop_VITIS_LOOP_22_3_proc5_U0_C_we0;
wire   [31:0] Loop_VITIS_LOOP_22_3_proc5_U0_C_d0;
wire    Loop_VITIS_LOOP_22_3_proc5_U0_strm_matrix1_read;
wire    Loop_VITIS_LOOP_22_3_proc5_U0_strm_matrix2_read;
wire    strm_matrix1_full_n;
wire   [127:0] strm_matrix1_dout;
wire    strm_matrix1_empty_n;
wire    strm_matrix2_full_n;
wire   [127:0] strm_matrix2_dout;
wire    strm_matrix2_empty_n;
wire   [0:0] start_for_Loop_VITIS_LOOP_22_3_proc5_U0_din;
wire    start_for_Loop_VITIS_LOOP_22_3_proc5_U0_full_n;
wire   [0:0] start_for_Loop_VITIS_LOOP_22_3_proc5_U0_dout;
wire    start_for_Loop_VITIS_LOOP_22_3_proc5_U0_empty_n;

controller_strm_matrix1_element_a #(
    .DataWidth( 32 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
strm_matrix1_element_a_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix1_element_a_address0),
    .ce0(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix1_element_a_ce0),
    .we0(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix1_element_a_we0),
    .d0(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix1_element_a_d0),
    .q0(strm_matrix1_element_a_q0),
    .address1(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix1_element_a_address1),
    .ce1(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix1_element_a_ce1),
    .q1(strm_matrix1_element_a_q1)
);

controller_strm_matrix1_element_a #(
    .DataWidth( 32 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
strm_matrix2_element_a_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix2_element_a_address0),
    .ce0(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix2_element_a_ce0),
    .we0(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix2_element_a_we0),
    .d0(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix2_element_a_d0),
    .q0(strm_matrix2_element_a_q0),
    .address1(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix2_element_a_address1),
    .ce1(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix2_element_a_ce1),
    .q1(strm_matrix2_element_a_q1)
);

controller_tmp_out #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
tmp_out_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(Loop_VITIS_LOOP_22_3_proc5_U0_block_out_out_address0),
    .ce0(Loop_VITIS_LOOP_22_3_proc5_U0_block_out_out_ce0),
    .we0(Loop_VITIS_LOOP_22_3_proc5_U0_block_out_out_we0),
    .d0(Loop_VITIS_LOOP_22_3_proc5_U0_block_out_out_d0),
    .q0(tmp_out_q0),
    .address1(Loop_VITIS_LOOP_22_3_proc5_U0_block_out_out_address1),
    .ce1(Loop_VITIS_LOOP_22_3_proc5_U0_block_out_out_ce1),
    .we1(Loop_VITIS_LOOP_22_3_proc5_U0_block_out_out_we1),
    .d1(Loop_VITIS_LOOP_22_3_proc5_U0_block_out_out_d1)
);

controller_Loop_VITIS_LOOP_11_1_proc4 Loop_VITIS_LOOP_11_1_proc4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Loop_VITIS_LOOP_11_1_proc4_U0_ap_start),
    .start_full_n(start_for_Loop_VITIS_LOOP_22_3_proc5_U0_full_n),
    .ap_done(Loop_VITIS_LOOP_11_1_proc4_U0_ap_done),
    .ap_continue(Loop_VITIS_LOOP_11_1_proc4_U0_ap_continue),
    .ap_idle(Loop_VITIS_LOOP_11_1_proc4_U0_ap_idle),
    .ap_ready(Loop_VITIS_LOOP_11_1_proc4_U0_ap_ready),
    .strm_matrix1_din(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix1_din),
    .strm_matrix1_full_n(strm_matrix1_full_n),
    .strm_matrix1_write(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix1_write),
    .strm_matrix2_din(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix2_din),
    .strm_matrix2_full_n(strm_matrix2_full_n),
    .strm_matrix2_write(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix2_write),
    .start_out(Loop_VITIS_LOOP_11_1_proc4_U0_start_out),
    .start_write(Loop_VITIS_LOOP_11_1_proc4_U0_start_write),
    .strm_matrix1_element_a_address0(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix1_element_a_address0),
    .strm_matrix1_element_a_ce0(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix1_element_a_ce0),
    .strm_matrix1_element_a_we0(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix1_element_a_we0),
    .strm_matrix1_element_a_d0(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix1_element_a_d0),
    .strm_matrix1_element_a_q0(strm_matrix1_element_a_q0),
    .strm_matrix1_element_a_address1(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix1_element_a_address1),
    .strm_matrix1_element_a_ce1(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix1_element_a_ce1),
    .strm_matrix1_element_a_q1(strm_matrix1_element_a_q1),
    .strm_matrix2_element_a_address0(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix2_element_a_address0),
    .strm_matrix2_element_a_ce0(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix2_element_a_ce0),
    .strm_matrix2_element_a_we0(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix2_element_a_we0),
    .strm_matrix2_element_a_d0(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix2_element_a_d0),
    .strm_matrix2_element_a_q0(strm_matrix2_element_a_q0),
    .strm_matrix2_element_a_address1(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix2_element_a_address1),
    .strm_matrix2_element_a_ce1(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix2_element_a_ce1),
    .strm_matrix2_element_a_q1(strm_matrix2_element_a_q1),
    .A_address0(Loop_VITIS_LOOP_11_1_proc4_U0_A_address0),
    .A_ce0(Loop_VITIS_LOOP_11_1_proc4_U0_A_ce0),
    .A_q0(A_q0),
    .B_address0(Loop_VITIS_LOOP_11_1_proc4_U0_B_address0),
    .B_ce0(Loop_VITIS_LOOP_11_1_proc4_U0_B_ce0),
    .B_q0(B_q0)
);

controller_Loop_VITIS_LOOP_22_3_proc5 Loop_VITIS_LOOP_22_3_proc5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Loop_VITIS_LOOP_22_3_proc5_U0_ap_start),
    .ap_done(Loop_VITIS_LOOP_22_3_proc5_U0_ap_done),
    .ap_continue(Loop_VITIS_LOOP_22_3_proc5_U0_ap_continue),
    .ap_idle(Loop_VITIS_LOOP_22_3_proc5_U0_ap_idle),
    .ap_ready(Loop_VITIS_LOOP_22_3_proc5_U0_ap_ready),
    .block_out_out_address0(Loop_VITIS_LOOP_22_3_proc5_U0_block_out_out_address0),
    .block_out_out_ce0(Loop_VITIS_LOOP_22_3_proc5_U0_block_out_out_ce0),
    .block_out_out_we0(Loop_VITIS_LOOP_22_3_proc5_U0_block_out_out_we0),
    .block_out_out_d0(Loop_VITIS_LOOP_22_3_proc5_U0_block_out_out_d0),
    .block_out_out_q0(tmp_out_q0),
    .block_out_out_address1(Loop_VITIS_LOOP_22_3_proc5_U0_block_out_out_address1),
    .block_out_out_ce1(Loop_VITIS_LOOP_22_3_proc5_U0_block_out_out_ce1),
    .block_out_out_we1(Loop_VITIS_LOOP_22_3_proc5_U0_block_out_out_we1),
    .block_out_out_d1(Loop_VITIS_LOOP_22_3_proc5_U0_block_out_out_d1),
    .C_address0(Loop_VITIS_LOOP_22_3_proc5_U0_C_address0),
    .C_ce0(Loop_VITIS_LOOP_22_3_proc5_U0_C_ce0),
    .C_we0(Loop_VITIS_LOOP_22_3_proc5_U0_C_we0),
    .C_d0(Loop_VITIS_LOOP_22_3_proc5_U0_C_d0),
    .strm_matrix1_dout(strm_matrix1_dout),
    .strm_matrix1_empty_n(strm_matrix1_empty_n),
    .strm_matrix1_read(Loop_VITIS_LOOP_22_3_proc5_U0_strm_matrix1_read),
    .strm_matrix2_dout(strm_matrix2_dout),
    .strm_matrix2_empty_n(strm_matrix2_empty_n),
    .strm_matrix2_read(Loop_VITIS_LOOP_22_3_proc5_U0_strm_matrix2_read)
);

controller_fifo_w128_d2_S strm_matrix1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix1_din),
    .if_full_n(strm_matrix1_full_n),
    .if_write(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix1_write),
    .if_dout(strm_matrix1_dout),
    .if_empty_n(strm_matrix1_empty_n),
    .if_read(Loop_VITIS_LOOP_22_3_proc5_U0_strm_matrix1_read)
);

controller_fifo_w128_d2_S strm_matrix2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix2_din),
    .if_full_n(strm_matrix2_full_n),
    .if_write(Loop_VITIS_LOOP_11_1_proc4_U0_strm_matrix2_write),
    .if_dout(strm_matrix2_dout),
    .if_empty_n(strm_matrix2_empty_n),
    .if_read(Loop_VITIS_LOOP_22_3_proc5_U0_strm_matrix2_read)
);

controller_start_for_Loop_VITIS_LOOP_22_3_proc5_U0 start_for_Loop_VITIS_LOOP_22_3_proc5_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Loop_VITIS_LOOP_22_3_proc5_U0_din),
    .if_full_n(start_for_Loop_VITIS_LOOP_22_3_proc5_U0_full_n),
    .if_write(Loop_VITIS_LOOP_11_1_proc4_U0_start_write),
    .if_dout(start_for_Loop_VITIS_LOOP_22_3_proc5_U0_dout),
    .if_empty_n(start_for_Loop_VITIS_LOOP_22_3_proc5_U0_empty_n),
    .if_read(Loop_VITIS_LOOP_22_3_proc5_U0_ap_ready)
);

assign A_address0 = Loop_VITIS_LOOP_11_1_proc4_U0_A_address0;

assign A_address1 = 6'd0;

assign A_ce0 = Loop_VITIS_LOOP_11_1_proc4_U0_A_ce0;

assign A_ce1 = 1'b0;

assign A_d0 = 32'd0;

assign A_d1 = 32'd0;

assign A_we0 = 1'b0;

assign A_we1 = 1'b0;

assign B_address0 = Loop_VITIS_LOOP_11_1_proc4_U0_B_address0;

assign B_address1 = 6'd0;

assign B_ce0 = Loop_VITIS_LOOP_11_1_proc4_U0_B_ce0;

assign B_ce1 = 1'b0;

assign B_d0 = 32'd0;

assign B_d1 = 32'd0;

assign B_we0 = 1'b0;

assign B_we1 = 1'b0;

assign C_address0 = Loop_VITIS_LOOP_22_3_proc5_U0_C_address0;

assign C_address1 = 6'd0;

assign C_ce0 = Loop_VITIS_LOOP_22_3_proc5_U0_C_ce0;

assign C_ce1 = 1'b0;

assign C_d0 = Loop_VITIS_LOOP_22_3_proc5_U0_C_d0;

assign C_d1 = 32'd0;

assign C_we0 = Loop_VITIS_LOOP_22_3_proc5_U0_C_we0;

assign C_we1 = 1'b0;

assign Loop_VITIS_LOOP_11_1_proc4_U0_ap_continue = 1'b1;

assign Loop_VITIS_LOOP_11_1_proc4_U0_ap_start = ap_start;

assign Loop_VITIS_LOOP_22_3_proc5_U0_ap_continue = 1'b1;

assign Loop_VITIS_LOOP_22_3_proc5_U0_ap_start = start_for_Loop_VITIS_LOOP_22_3_proc5_U0_empty_n;

assign ap_done = Loop_VITIS_LOOP_22_3_proc5_U0_ap_done;

assign ap_idle = (Loop_VITIS_LOOP_22_3_proc5_U0_ap_idle & Loop_VITIS_LOOP_11_1_proc4_U0_ap_idle);

assign ap_ready = Loop_VITIS_LOOP_11_1_proc4_U0_ap_ready;

assign start_for_Loop_VITIS_LOOP_22_3_proc5_U0_din = 1'b1;

endmodule //controller
