// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module top_matrix_multiply_blockmatmul (
        ap_clk,
        ap_rst,
        strm_matrix1_dout,
        strm_matrix1_empty_n,
        strm_matrix1_read,
        strm_matrix2_dout,
        strm_matrix2_empty_n,
        strm_matrix2_read,
        strm_ABpartial_din,
        strm_ABpartial_full_n,
        strm_ABpartial_write,
        it,
        it_ap_vld,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input   ap_clk;
input   ap_rst;
input  [127:0] strm_matrix1_dout;
input   strm_matrix1_empty_n;
output   strm_matrix1_read;
input  [127:0] strm_matrix2_dout;
input   strm_matrix2_empty_n;
output   strm_matrix2_read;
output  [511:0] strm_ABpartial_din;
input   strm_ABpartial_full_n;
output   strm_ABpartial_write;
input  [0:0] it;
input   it_ap_vld;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire   [31:0] AB_local_i_q0;
wire   [31:0] AB_local_i_q1;
wire   [31:0] AB_local_t_q0;
wire   [31:0] AB_local_t_q1;
wire    blockmatmul_Block_split26_proc1_U0_ap_start;
wire    blockmatmul_Block_split26_proc1_U0_ap_done;
wire    blockmatmul_Block_split26_proc1_U0_ap_continue;
wire    blockmatmul_Block_split26_proc1_U0_ap_idle;
wire    blockmatmul_Block_split26_proc1_U0_ap_ready;
wire    blockmatmul_Block_split26_proc1_U0_start_out;
wire    blockmatmul_Block_split26_proc1_U0_start_write;
wire    blockmatmul_Block_split26_proc1_U0_strm_matrix1_read;
wire   [31:0] blockmatmul_Block_split26_proc1_U0_A_din;
wire    blockmatmul_Block_split26_proc1_U0_A_write;
wire    blockmatmul_Loop_2_proc2_U0_ap_start;
wire    blockmatmul_Loop_2_proc2_U0_ap_done;
wire    blockmatmul_Loop_2_proc2_U0_ap_continue;
wire    blockmatmul_Loop_2_proc2_U0_ap_idle;
wire    blockmatmul_Loop_2_proc2_U0_ap_ready;
wire   [3:0] blockmatmul_Loop_2_proc2_U0_AB_local_address0;
wire    blockmatmul_Loop_2_proc2_U0_AB_local_ce0;
wire    blockmatmul_Loop_2_proc2_U0_AB_local_we0;
wire   [31:0] blockmatmul_Loop_2_proc2_U0_AB_local_d0;
wire   [3:0] blockmatmul_Loop_2_proc2_U0_AB_local_address1;
wire    blockmatmul_Loop_2_proc2_U0_AB_local_ce1;
wire    blockmatmul_Loop_2_proc2_U0_strm_matrix2_read;
wire    blockmatmul_Loop_2_proc2_U0_A_read;
wire    blockmatmul_Loop_writeoutput_proc_U0_ap_start;
wire    blockmatmul_Loop_writeoutput_proc_U0_ap_done;
wire    blockmatmul_Loop_writeoutput_proc_U0_ap_continue;
wire    blockmatmul_Loop_writeoutput_proc_U0_ap_idle;
wire    blockmatmul_Loop_writeoutput_proc_U0_ap_ready;
wire   [31:0] blockmatmul_Loop_writeoutput_proc_U0_temp_out_out_din;
wire    blockmatmul_Loop_writeoutput_proc_U0_temp_out_out_write;
wire    blockmatmul_Loop_writeoutput_proc_U0_start_out;
wire    blockmatmul_Loop_writeoutput_proc_U0_start_write;
wire   [3:0] blockmatmul_Loop_writeoutput_proc_U0_AB_local_address0;
wire    blockmatmul_Loop_writeoutput_proc_U0_AB_local_ce0;
wire    blockmatmul_Block_split23_proc3_U0_ap_start;
wire    blockmatmul_Block_split23_proc3_U0_ap_done;
wire    blockmatmul_Block_split23_proc3_U0_ap_continue;
wire    blockmatmul_Block_split23_proc3_U0_ap_idle;
wire    blockmatmul_Block_split23_proc3_U0_ap_ready;
wire    blockmatmul_Block_split23_proc3_U0_temp_out_out_read;
wire   [511:0] blockmatmul_Block_split23_proc3_U0_strm_ABpartial_din;
wire    blockmatmul_Block_split23_proc3_U0_strm_ABpartial_write;
wire    AB_local_i_full_n;
wire    AB_local_t_empty_n;
wire    A_full_n;
wire   [31:0] A_dout;
wire    A_empty_n;
wire    temp_out_out_full_n;
wire   [31:0] temp_out_out_dout;
wire    temp_out_out_empty_n;
wire   [0:0] start_for_blockmatmul_Loop_2_proc2_U0_din;
wire    start_for_blockmatmul_Loop_2_proc2_U0_full_n;
wire   [0:0] start_for_blockmatmul_Loop_2_proc2_U0_dout;
wire    start_for_blockmatmul_Loop_2_proc2_U0_empty_n;
wire   [0:0] start_for_blockmatmul_Block_split23_proc3_U0_din;
wire    start_for_blockmatmul_Block_split23_proc3_U0_full_n;
wire   [0:0] start_for_blockmatmul_Block_split23_proc3_U0_dout;
wire    start_for_blockmatmul_Block_split23_proc3_U0_empty_n;

top_matrix_multiply_blockmatmul_AB_local #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
AB_local_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(blockmatmul_Loop_2_proc2_U0_AB_local_address0),
    .i_ce0(blockmatmul_Loop_2_proc2_U0_AB_local_ce0),
    .i_we0(blockmatmul_Loop_2_proc2_U0_AB_local_we0),
    .i_d0(blockmatmul_Loop_2_proc2_U0_AB_local_d0),
    .i_q0(AB_local_i_q0),
    .i_address1(blockmatmul_Loop_2_proc2_U0_AB_local_address1),
    .i_ce1(blockmatmul_Loop_2_proc2_U0_AB_local_ce1),
    .i_q1(AB_local_i_q1),
    .t_address0(blockmatmul_Loop_writeoutput_proc_U0_AB_local_address0),
    .t_ce0(blockmatmul_Loop_writeoutput_proc_U0_AB_local_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(AB_local_t_q0),
    .t_address1(4'd0),
    .t_ce1(1'b0),
    .t_q1(AB_local_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(AB_local_i_full_n),
    .i_write(blockmatmul_Loop_2_proc2_U0_ap_done),
    .t_empty_n(AB_local_t_empty_n),
    .t_read(blockmatmul_Loop_writeoutput_proc_U0_ap_ready)
);

top_matrix_multiply_blockmatmul_Block_split26_proc1 blockmatmul_Block_split26_proc1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(blockmatmul_Block_split26_proc1_U0_ap_start),
    .start_full_n(start_for_blockmatmul_Loop_2_proc2_U0_full_n),
    .ap_done(blockmatmul_Block_split26_proc1_U0_ap_done),
    .ap_continue(blockmatmul_Block_split26_proc1_U0_ap_continue),
    .ap_idle(blockmatmul_Block_split26_proc1_U0_ap_idle),
    .ap_ready(blockmatmul_Block_split26_proc1_U0_ap_ready),
    .start_out(blockmatmul_Block_split26_proc1_U0_start_out),
    .start_write(blockmatmul_Block_split26_proc1_U0_start_write),
    .it(it),
    .strm_matrix1_dout(strm_matrix1_dout),
    .strm_matrix1_empty_n(strm_matrix1_empty_n),
    .strm_matrix1_read(blockmatmul_Block_split26_proc1_U0_strm_matrix1_read),
    .A_din(blockmatmul_Block_split26_proc1_U0_A_din),
    .A_full_n(A_full_n),
    .A_write(blockmatmul_Block_split26_proc1_U0_A_write)
);

top_matrix_multiply_blockmatmul_Loop_2_proc2 blockmatmul_Loop_2_proc2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(blockmatmul_Loop_2_proc2_U0_ap_start),
    .ap_done(blockmatmul_Loop_2_proc2_U0_ap_done),
    .ap_continue(blockmatmul_Loop_2_proc2_U0_ap_continue),
    .ap_idle(blockmatmul_Loop_2_proc2_U0_ap_idle),
    .ap_ready(blockmatmul_Loop_2_proc2_U0_ap_ready),
    .AB_local_address0(blockmatmul_Loop_2_proc2_U0_AB_local_address0),
    .AB_local_ce0(blockmatmul_Loop_2_proc2_U0_AB_local_ce0),
    .AB_local_we0(blockmatmul_Loop_2_proc2_U0_AB_local_we0),
    .AB_local_d0(blockmatmul_Loop_2_proc2_U0_AB_local_d0),
    .AB_local_address1(blockmatmul_Loop_2_proc2_U0_AB_local_address1),
    .AB_local_ce1(blockmatmul_Loop_2_proc2_U0_AB_local_ce1),
    .AB_local_q1(AB_local_i_q1),
    .strm_matrix2_dout(strm_matrix2_dout),
    .strm_matrix2_empty_n(strm_matrix2_empty_n),
    .strm_matrix2_read(blockmatmul_Loop_2_proc2_U0_strm_matrix2_read),
    .A_dout(A_dout),
    .A_empty_n(A_empty_n),
    .A_read(blockmatmul_Loop_2_proc2_U0_A_read)
);

top_matrix_multiply_blockmatmul_Loop_writeoutput_proc blockmatmul_Loop_writeoutput_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(blockmatmul_Loop_writeoutput_proc_U0_ap_start),
    .start_full_n(start_for_blockmatmul_Block_split23_proc3_U0_full_n),
    .ap_done(blockmatmul_Loop_writeoutput_proc_U0_ap_done),
    .ap_continue(blockmatmul_Loop_writeoutput_proc_U0_ap_continue),
    .ap_idle(blockmatmul_Loop_writeoutput_proc_U0_ap_idle),
    .ap_ready(blockmatmul_Loop_writeoutput_proc_U0_ap_ready),
    .temp_out_out_din(blockmatmul_Loop_writeoutput_proc_U0_temp_out_out_din),
    .temp_out_out_full_n(temp_out_out_full_n),
    .temp_out_out_write(blockmatmul_Loop_writeoutput_proc_U0_temp_out_out_write),
    .start_out(blockmatmul_Loop_writeoutput_proc_U0_start_out),
    .start_write(blockmatmul_Loop_writeoutput_proc_U0_start_write),
    .AB_local_address0(blockmatmul_Loop_writeoutput_proc_U0_AB_local_address0),
    .AB_local_ce0(blockmatmul_Loop_writeoutput_proc_U0_AB_local_ce0),
    .AB_local_q0(AB_local_t_q0)
);

top_matrix_multiply_blockmatmul_Block_split23_proc3 blockmatmul_Block_split23_proc3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(blockmatmul_Block_split23_proc3_U0_ap_start),
    .ap_done(blockmatmul_Block_split23_proc3_U0_ap_done),
    .ap_continue(blockmatmul_Block_split23_proc3_U0_ap_continue),
    .ap_idle(blockmatmul_Block_split23_proc3_U0_ap_idle),
    .ap_ready(blockmatmul_Block_split23_proc3_U0_ap_ready),
    .temp_out_out_dout(temp_out_out_dout),
    .temp_out_out_empty_n(temp_out_out_empty_n),
    .temp_out_out_read(blockmatmul_Block_split23_proc3_U0_temp_out_out_read),
    .strm_ABpartial_din(blockmatmul_Block_split23_proc3_U0_strm_ABpartial_din),
    .strm_ABpartial_full_n(strm_ABpartial_full_n),
    .strm_ABpartial_write(blockmatmul_Block_split23_proc3_U0_strm_ABpartial_write)
);

top_matrix_multiply_fifo_w32_d32_S A_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(blockmatmul_Block_split26_proc1_U0_A_din),
    .if_full_n(A_full_n),
    .if_write(blockmatmul_Block_split26_proc1_U0_A_write),
    .if_dout(A_dout),
    .if_empty_n(A_empty_n),
    .if_read(blockmatmul_Loop_2_proc2_U0_A_read)
);

top_matrix_multiply_fifo_w32_d16_S temp_out_out_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(blockmatmul_Loop_writeoutput_proc_U0_temp_out_out_din),
    .if_full_n(temp_out_out_full_n),
    .if_write(blockmatmul_Loop_writeoutput_proc_U0_temp_out_out_write),
    .if_dout(temp_out_out_dout),
    .if_empty_n(temp_out_out_empty_n),
    .if_read(blockmatmul_Block_split23_proc3_U0_temp_out_out_read)
);

top_matrix_multiply_start_for_blockmatmul_Loop_2_proc2_U0 start_for_blockmatmul_Loop_2_proc2_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_blockmatmul_Loop_2_proc2_U0_din),
    .if_full_n(start_for_blockmatmul_Loop_2_proc2_U0_full_n),
    .if_write(blockmatmul_Block_split26_proc1_U0_start_write),
    .if_dout(start_for_blockmatmul_Loop_2_proc2_U0_dout),
    .if_empty_n(start_for_blockmatmul_Loop_2_proc2_U0_empty_n),
    .if_read(blockmatmul_Loop_2_proc2_U0_ap_ready)
);

top_matrix_multiply_start_for_blockmatmul_Block_split23_proc3_U0 start_for_blockmatmul_Block_split23_proc3_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_blockmatmul_Block_split23_proc3_U0_din),
    .if_full_n(start_for_blockmatmul_Block_split23_proc3_U0_full_n),
    .if_write(blockmatmul_Loop_writeoutput_proc_U0_start_write),
    .if_dout(start_for_blockmatmul_Block_split23_proc3_U0_dout),
    .if_empty_n(start_for_blockmatmul_Block_split23_proc3_U0_empty_n),
    .if_read(blockmatmul_Block_split23_proc3_U0_ap_ready)
);

assign ap_done = blockmatmul_Block_split23_proc3_U0_ap_done;

assign ap_idle = ((1'b1 ^ AB_local_t_empty_n) & blockmatmul_Loop_writeoutput_proc_U0_ap_idle & blockmatmul_Loop_2_proc2_U0_ap_idle & blockmatmul_Block_split26_proc1_U0_ap_idle & blockmatmul_Block_split23_proc3_U0_ap_idle);

assign ap_ready = blockmatmul_Block_split26_proc1_U0_ap_ready;

assign blockmatmul_Block_split23_proc3_U0_ap_continue = ap_continue;

assign blockmatmul_Block_split23_proc3_U0_ap_start = start_for_blockmatmul_Block_split23_proc3_U0_empty_n;

assign blockmatmul_Block_split26_proc1_U0_ap_continue = 1'b1;

assign blockmatmul_Block_split26_proc1_U0_ap_start = ap_start;

assign blockmatmul_Loop_2_proc2_U0_ap_continue = AB_local_i_full_n;

assign blockmatmul_Loop_2_proc2_U0_ap_start = start_for_blockmatmul_Loop_2_proc2_U0_empty_n;

assign blockmatmul_Loop_writeoutput_proc_U0_ap_continue = 1'b1;

assign blockmatmul_Loop_writeoutput_proc_U0_ap_start = AB_local_t_empty_n;

assign start_for_blockmatmul_Block_split23_proc3_U0_din = 1'b1;

assign start_for_blockmatmul_Loop_2_proc2_U0_din = 1'b1;

assign strm_ABpartial_din = blockmatmul_Block_split23_proc3_U0_strm_ABpartial_din;

assign strm_ABpartial_write = blockmatmul_Block_split23_proc3_U0_strm_ABpartial_write;

assign strm_matrix1_read = blockmatmul_Block_split26_proc1_U0_strm_matrix1_read;

assign strm_matrix2_read = blockmatmul_Loop_2_proc2_U0_strm_matrix2_read;

endmodule //top_matrix_multiply_blockmatmul
